apiVersion: v1
kind: ConfigMap
metadata:
  name: afterpay-add-on-1-config
  namespace: development
  labels:
    app: afterpay
    add-on: add-on-1
    cluster: cluster-1
    environment: development
data:
  platform: "afterpay"
  add_on: "add-on-1"
  cluster: "cluster-1"
  environment: "development"
