apiVersion: v1
kind: ConfigMap
metadata:
  name: afterpay-add-on-1-config
  namespace: production
  labels:
    app: afterpay
    add-on: add-on-1
    cluster: cluster-2
    environment: production
data:
  platform: "afterpay"
  add_on: "add-on-1"
  cluster: "cluster-2"
  environment: "production"
