apiVersion: v1
kind: ConfigMap
metadata:
  name: square-add-on-1-config
  namespace: development
  labels:
    app: square
    add-on: add-on-1
    cluster: cluster-1
    environment: development
data:
  platform: "square"
  add_on: "add-on-1"
  cluster: "cluster-1"
  environment: "development"
