apiVersion: v1
kind: ConfigMap
metadata:
  name: afterpay-add-on-2-config
  namespace: development
  labels:
    app: afterpay
    add-on: add-on-2
    cluster: cluster-2
    environment: development
data:
  platform: "afterpay"
  add_on: "add-on-2"
  cluster: "cluster-2"
  environment: "development"
