apiVersion: v1
kind: ConfigMap
metadata:
  name: afterpay-add-on-2-config
  namespace: staging
  labels:
    app: afterpay
    add-on: add-on-2
    cluster: cluster-1
    environment: staging
data:
  platform: "afterpay"
  add_on: "add-on-2"
  cluster: "cluster-1"
  environment: "staging"
