apiVersion: v1
kind: ConfigMap
metadata:
  name: cash-add-on-1-config
  namespace: production
  labels:
    app: cash
    add-on: add-on-1
    cluster: cluster-1
    environment: production
data:
  platform: "cash"
  add_on: "add-on-1"
  cluster: "cluster-1"
  environment: "production"
